# Configuração para ambiente de produção (AWS) - SEM SEGURANÇA
server:
  port: 8080

# Configurações de segurança DESABILITADA
security:
  enabled: false

spring:
  application:
    name: leitor-transacoes-ia
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://financas-prd-mysql.cyr6a800ez9a.us-east-1.rds.amazonaws.com:3306/mysql}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:appuser}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  # Flyway Database Migration Configuration
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

cloud:
  aws:
    region:
      static: ${AWS_REGION:us-east-1}
      sts:
        enabled: true

# Configurações AWS básicas
aws:
  region: ${AWS_REGION:us-east-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    enabled: false
  tracing:
    sampling:
      probability: 0.1

# Configurações de logging para produção
logging:
  level:
    root: INFO
    br.com.financas.leitor_transacoes_ia: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Configurações de multitenancy
multitenancy:
  enabled: true
  default-user-id: "user-123-hardcoded"
