name: Test Secrets and Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test-secrets.yml'

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "🔍 Testing AWS credentials..."
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "❌ AWS_ACCESS_KEY_ID is not set"
            exit 1
          fi
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "❌ AWS_SECRET_ACCESS_KEY is not set"
            exit 1
          fi
          
          echo "✅ AWS credentials are set"
          echo "Testing AWS CLI..."
          aws sts get-caller-identity || echo "⚠️ AWS CLI test failed"

      - name: Test Docker Hub credentials
        run: |
          echo "🔍 Testing Docker Hub credentials..."
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "❌ DOCKERHUB_USERNAME is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN is not set"
            exit 1
          fi
          
          echo "✅ Docker Hub credentials are set"
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Test workflow completion
        run: |
          echo "✅ All secrets are configured correctly!"
          echo "🚀 GitHub Actions workflow is ready to use"
